name: Build and publish a release to PyPI

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/mergr
    permissions:
      id-token: write
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-pdm-env

      - name: Run checks
        run: make check

      - name: Run tests
        run: make test

      - name: Export tag
        id: vars
        run: echo tag=${GITHUB_REF#refs/*/} >> $GITHUB_OUTPUT

      - name: Build new release
        run: |
          source .venv/bin/activate
          export PDM_BUILD_SCM_VERSION=$RELEASE_VERSION
          make build
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
